### ISSUE TITLE
Blue butterflies are not correctly segmented

### ISSUE THREAD

**Issue by stefanv** [machine-shop/butterfly-wings#38]
We could look into using more color information in the segmentation.  Since the background is also present at the top-left corner of the image, we could sample that region to determine its color more closely.

**Comment by RebeccaJWilson** [comment]
Hi Stefan. Below are some examples of specimens that are not working correctly for Blue butterfly species (one male and female each for 3 different species).

![BMNHE_1362731_162415_35a21c7ed0aa3976d4bdcc4e46c8b4fe25da89a4](https://user-images.githubusercontent.com/48092348/54552382-d7c6b200-49a7-11e9-87c2-ba601e369f0b.JPG)
![BMNHE_1362753_162438_cbe32fb34753c4d943a0e0f3b090046a7f2ffcef](https://user-images.githubusercontent.com/48092348/54552392-e01eed00-49a7-11e9-8ad4-5d0116817a3b.JPG)
![BMNHE_1150161_119418_b22d49ad7b4d2359f9d9f351ef592c3a3bea48b9](https://user-images.githubusercontent.com/48092348/54552430-faf16180-49a7-11e9-93fc-f379956c74c0.JPG)
![BMNHE_1285536_122072_d9c99cbf8ec22fc2e82c2498b800a730559af459](https://user-images.githubusercontent.com/48092348/54552464-06dd2380-49a8-11e9-9aba-3986f9f08af2.JPG)
![BMNHE_1373178](https://user-images.githubusercontent.com/48092348/54552579-53c0fa00-49a8-11e9-9b99-08dfe8afcd15.JPG)
![BMNHE_1374815](https://user-images.githubusercontent.com/48092348/54552588-5a4f7180-49a8-11e9-93d1-1f9a676b70bc.JPG)

**Comment by alexdesiqueira** [comment]
Hi Stéfan, Rebecca,
this is possibly solved by #50.

**Comment by alexdesiqueira** [comment]
Closing; solved by #52. Please reopen if necessary.
