### ISSUE TITLE
README file is incomplete

### ISSUE THREAD

**Issue by stefanv** [machine-shop/butterfly-wings#4]
It does not provide enough instructions on how to get started.

1. How to install the requirements (are we missing a `requirements.txt` file?)
2. How to obtain some initial test data (do we have a single image checked in that the user can test on?)
3. How to do an example run (the description given outlines all possible flags, instead of showing an example command execution)

Further, let's remove the help string, and rather remind the user that `./pipeline.py --help` gives all options.

**Comment by denniscfeng** [comment]
Old issue from before we made the current version of the readme
