### ISSUE TITLE
Notebooks should be run as part of the unit tests

### ISSUE THREAD

**Issue by stefanv** [machine-shop/butterfly-wings#5]
Notebooks that are not executed as part of the unit test suite are likely broken, or should be considered so.

```bash
$ jupyter nbconvert --to notebook --execute mynotebook.ipynb --output mynotebook.ipynb
```

**Comment by denniscfeng** [comment]
Notebooks have been removed, since they're bulky and also originally prototyping code that we've since done a lot of improvement on
